name: MkDocs
on:
  push:
    branches: 
      - master
      - main
    paths:
      - 'www/*'
      - 'www/docs/*'
      - '.github/workflows/mkdocs.yaml'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs-material 
      - run: mkdocs gh-deploy --force --config-file ./www/mkdocs.yml
